#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"
mkdir -p logs

PIPE_TAG="${PIPE_TAG:-td3_mpcclone_tuned_$(date +%Y%m%d_%H%M%S)}"
PARTITION="${PARTITION:-tier3}"
TIME_LIMIT="${TIME_LIMIT:-18:00:00}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEM_GB="${MEM_GB:-40G}"

# Slightly stronger than the quick baseline, but still bounded for debug.
MPC_DATASET_SETUPS="${MPC_DATASET_SETUPS:-18}"
MPC_MAX_STEPS="${MPC_MAX_STEPS:-500}"
MPC_REPLAN_EVERY="${MPC_REPLAN_EVERY:-2}"
MPC_HORIZON="${MPC_HORIZON:-48}"
MPC_ITERS="${MPC_ITERS:-16}"
MPC_MODEL_SUBSTEPS="${MPC_MODEL_SUBSTEPS:-3}"

TD3_TOTAL_ENV_STEPS="${TD3_TOTAL_ENV_STEPS:-450000}"
TD3_PREFILL_MAX_SAMPLES="${TD3_PREFILL_MAX_SAMPLES:-225000}"
TD3_EXPL_NOISE_START="${TD3_EXPL_NOISE_START:-0.06}"
TD3_EXPL_NOISE_END="${TD3_EXPL_NOISE_END:-0.01}"
TD3_EXPL_DECAY_STEPS="${TD3_EXPL_DECAY_STEPS:-250000}"

TD3_W_POS="${TD3_W_POS:-28.0}"
TD3_W_VEL="${TD3_W_VEL:-16.0}"
TD3_W_FUEL="${TD3_W_FUEL:-0.0002}"
TD3_W_NEAR_COLLISION="${TD3_W_NEAR_COLLISION:-30.0}"
TD3_W_COLLISION="${TD3_W_COLLISION:-700.0}"
TD3_W_ESCAPE="${TD3_W_ESCAPE:-80.0}"
TD3_W_SWITCH="${TD3_W_SWITCH:-0.06}"
TD3_W_PHASE="${TD3_W_PHASE:-0.25}"

echo "Submitting TD3 MPC-clone TUNED pipeline"
echo "PIPE_TAG=$PIPE_TAG"
echo "PARTITION=$PARTITION TIME=$TIME_LIMIT CPU=$CPUS_PER_TASK MEM=$MEM_GB"
echo "MPC_DATASET_SETUPS=$MPC_DATASET_SETUPS MPC_HORIZON=$MPC_HORIZON MPC_ITERS=$MPC_ITERS"
echo "TD3_TOTAL_ENV_STEPS=$TD3_TOTAL_ENV_STEPS TD3_EXPL=$TD3_EXPL_NOISE_START->$TD3_EXPL_NOISE_END"
echo "TD3 weights: pos=$TD3_W_POS vel=$TD3_W_VEL fuel=$TD3_W_FUEL near=$TD3_W_NEAR_COLLISION collision=$TD3_W_COLLISION"

JOB_ID=$(
  sbatch --parsable \
    --partition="$PARTITION" \
    --time="$TIME_LIMIT" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEM_GB" \
    --export=ALL,PIPE_TAG="$PIPE_TAG",MPC_DATASET_SETUPS="$MPC_DATASET_SETUPS",MPC_MAX_STEPS="$MPC_MAX_STEPS",MPC_REPLAN_EVERY="$MPC_REPLAN_EVERY",MPC_HORIZON="$MPC_HORIZON",MPC_ITERS="$MPC_ITERS",MPC_MODEL_SUBSTEPS="$MPC_MODEL_SUBSTEPS",TD3_TOTAL_ENV_STEPS="$TD3_TOTAL_ENV_STEPS",TD3_PREFILL_MAX_SAMPLES="$TD3_PREFILL_MAX_SAMPLES",TD3_EXPL_NOISE_START="$TD3_EXPL_NOISE_START",TD3_EXPL_NOISE_END="$TD3_EXPL_NOISE_END",TD3_EXPL_DECAY_STEPS="$TD3_EXPL_DECAY_STEPS",TD3_W_POS="$TD3_W_POS",TD3_W_VEL="$TD3_W_VEL",TD3_W_FUEL="$TD3_W_FUEL",TD3_W_NEAR_COLLISION="$TD3_W_NEAR_COLLISION",TD3_W_COLLISION="$TD3_W_COLLISION",TD3_W_ESCAPE="$TD3_W_ESCAPE",TD3_W_SWITCH="$TD3_W_SWITCH",TD3_W_PHASE="$TD3_W_PHASE" \
    sbatch_td3_mpc_clone_pipeline.sh
)

echo "JOB_ID=$JOB_ID"
echo "PIPE_TAG=$PIPE_TAG"
echo "Track:"
echo "  squeue -j $JOB_ID"
echo "Logs:"
echo "  logs/csci1470_td3_mpcclone_${JOB_ID}.out"
echo "  logs/csci1470_td3_mpcclone_${JOB_ID}.err"
